//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularAdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int personel_no { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cinsiyet { get; set; }
        public string dogum_tarihi { get; set; }
        public string baslama_tarihi { get; set; }
        public string calisma_saati { get; set; }
        public string maas { get; set; }
        public string prim { get; set; }
        public string unvan { get; set; }
        public string birim { get; set; }
        public string il { get; set; }
    }
}
