//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularAdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public int id { get; set; }
        public string urunadi { get; set; }
        public string urunfiyat { get; set; }
        public string urunkategori { get; set; }
        public string urunadres { get; set; }
        public string urunfoto { get; set; }
    }
}
